apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: release-workflow2
on:
  workflow_dispatch:
    inputs:
      manisfest:
        type: string
        required: true
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
